module fft_module (
    
    input clk,
    input rst,
    
    input signed [15:0] x_real, //Real part of sample
    input signed [15:0] x_imag, //Imaginary part of sample
    input out_valid, //Valid sample
    output in_ready, //Sample can be inputted
    
    output signed [15:0] X_real, //Real part of output
    output signed [15:0] X_imag, //Imaginary part of output
    input out_ready, //Value can be outputted
    output in_valid //Output is valid
   
);
    reg in_ready_r;
    reg signed [15:0] X_real_r;
    reg signed [15:0] X_imag_r;
    reg in_valid_r;
    
    assign X_real = X_real_r;
    assign X_imag = X_imag_r;
    assign in_ready = in_ready_r;
    assign in_valid = in_valid_r;
    
    wire signed [15:0] A_re; //Real part of A into RAM
    wire signed [15:0] A_im; //Imag part of A into RAM
    wire signed [15:0] B_re; //Real part of B into RAM
    wire signed [15:0] B_im; //Imag part of B into RAM
    
    wire [3:0] A_address; //A address in RAM
    wire [3:0] B_address; //B address in RAM
    
    wire read_select; //Select which ram module to read from
    assign read_selecter = read_select;
    
    wire signed [15:0] A_pr; //RAM output A_real
    wire signed [15:0] A_pi; //RAM output A_imag
    wire signed [15:0] B_pr; //RAM output B_real
    wire signed [15:0] B_pi; //RAM output B_imag
    
    wire WE0;
    assign write_enable_0 = WE0;
    wire WE1;
    assign write_enable_1 = WE1;
    
    //Manually read or write data
    reg io_mode;
    
    ram_module ram ( //RAM module
        .clk(clk),
        .A_re(A_re),
        .A_im(A_im),
        .B_re(B_re),
        .B_im(B_im),
        
        .A(A_address),
        .B(B_address),
        
        .WE0(WE0),
        .WE1(WE1),
        
        .load_one_val(io_mode),
        
        .read_select(read_select),
        
        .A_pr(A_pr),
        .A_pi(A_pi),
        .B_pr(B_pr),
        .B_pi(B_pi)
    );
    
    reg start_ready; //Start calculating addresses
    wire out_done; //Done calculating all values
    
    wire butterfly_done; //Butterfly module has completed calculation
    wire butterfly_out; //Butterfly module can output values
    wire butterfly_start; //Butterfly module can start calculation
    wire [3:0] agu_A_address; //A Address generated by agu
    wire [3:0] agu_B_address; //B Address generated by agu
    
    assign agu_a = agu_A_address;
    assign agu_b = agu_B_address;
    
    wire agu_WE0; //WE0 generated by AGU
    wire agu_WE1; //WE1 generated by AGU
    
    wire [2:0] twiddle_address; //Twiddle address to ROM
    assign twiddle_addr = twiddle_address;
    
    address_generator agu( //Generate the addresses for calculations and handle timings
        .clk(clk),
        .rst(rst),
        
        .start_ready(start_ready),
        .out_done(out_done),
        .bfu_valid(butterfly_done),
        .bfu_out(butterfly_out),
        .bfu_ready(butterfly_start),
        
        .A(agu_A_address),
        .B(agu_B_address),
        
        .read_select(read_select),
        .WE0(agu_WE0),
        .WE1(agu_WE1),
        .twiddle_address(twiddle_address)
    );
    
    wire signed [15:0] twiddle_re; //Real part of twiddle factor from ROM
    wire signed [15:0] twiddle_im; //Imaginary part of twiddle factor from ROM
    
    twiddle_rom twiddle_rom_mod ( //Rom that stores the twiddle factors
        .clk(clk),
        .address(twiddle_address),
        
        .W_r(twiddle_re),
        .W_i(twiddle_im)
    );
    
    wire signed [15:0] butterfly_A_re; //Butterfly output A_real
    wire signed [15:0] butterfly_A_im; //Butterfly output A_imag
    wire signed [15:0] butterfly_B_re; //Butterfly output B_real
    wire signed [15:0] butterfly_B_im; //Butterfly output B_imag

    butterfly_module butterfly_mod( //Butterfly module that performs the calculations
        .clk(clk),
        .rst(rst),
        
        .A_real(A_pr),
        .A_imag(A_pi),
        .B_real(B_pr),
        .B_imag(B_pi),
        .W_real(twiddle_re),
        .W_imag(twiddle_im),
        
        .input_ready(butterfly_start),
        .out_ready(butterfly_out),
        
        .res_Ar(butterfly_A_re),
        .res_Ai(butterfly_A_im),
        .res_Br(butterfly_B_re),
        .res_Bi(butterfly_B_im),
        
        .out_valid(butterfly_done) 
    );
    
    //Manually write enable, always true at the start to load data in
    reg internal_WE0;
    reg internal_WE1;
    
    //Internal address registers for loading/reading data, used for outputting values
    reg [3:0] internal_A;
    reg [3:0] internal_B;
    
    //Internal registers for when loading in data
    reg signed [15:0] internal_A_re;
    reg signed [15:0] internal_A_im;
    reg signed [15:0] internal_B_re;
    reg signed [15:0] internal_B_im;
    
    assign A_address = io_mode ? internal_A : agu_A_address;
    assign B_address = io_mode ? internal_B : agu_B_address;
    
    assign A_re = io_mode ? internal_A_re : butterfly_A_re;
    assign A_im = io_mode ? internal_A_im : butterfly_A_im;
    assign B_re = io_mode ? internal_B_re : butterfly_B_re;
    assign B_im = io_mode ? internal_B_im : butterfly_B_im;
    
    assign WE0 = io_mode ? internal_WE0 : agu_WE0;
    assign WE1 = io_mode ? internal_WE1 : agu_WE1;
    
    reg [1:0] state;
    assign cur_state = state;
    
    localparam STATE_LOAD = 2'd0;
    localparam STATE_WRITE = 2'd1;
    localparam STATE_CALCULATE = 2'd2;
    localparam STATE_OUTPUT = 2'd3;
    
    reg [3:0] load_samples_cnt; //Count how many times samples have been loaded in
    reg [3:0] output_cnt;
    reg [2:0] read_pipeline;
    
    assign read_pipe_count = read_pipeline;
    assign output_counter = output_cnt;
    always @ (posedge clk or posedge rst) begin
        
        if(rst) begin
            start_ready <= 1'b0;
            internal_WE0 <= 1'b0;
            internal_WE1 <= 1'b0;
            io_mode <= 1'b1;
            internal_A <= 4'b0;
            internal_B <= 4'b0;
            state <= 2'd0;
            load_samples_cnt <= 4'd0;
            
            in_ready_r <= 1'b0;
            X_real_r <= 16'b0;
            X_imag_r <= 16'b0;
            in_valid_r <= 1'b0;
            
            output_cnt <= 4'b0;
            read_pipeline <= 3'b0;
            
            internal_A_re <= 16'b0;
            internal_A_im <= 16'b0;
            internal_B_re <= 16'b0;
            internal_B_im <= 16'b0;
        end else begin
            
            case(state)
                
                STATE_LOAD: begin
                    internal_WE0 <= 1'b0;
                    in_ready_r <= 1'b1;
                    if(out_valid) begin
                        internal_A_re <= x_real;
                        internal_A_im <= x_imag;
                        internal_A <= {load_samples_cnt[0], load_samples_cnt[1], load_samples_cnt[2], load_samples_cnt[3]};
                        state <= STATE_WRITE;
                    end
                end
                
                STATE_WRITE: begin
                    in_ready_r <= 1'b0;
                    internal_WE0 <= 1'b1;
                    if(load_samples_cnt == 4'd15) begin
                        state <= STATE_CALCULATE;
                    end else begin
                        load_samples_cnt <= load_samples_cnt + 1;
                        state <= STATE_LOAD;
                    end
                end
                
                STATE_CALCULATE: begin
                    io_mode <= 1'b0;
                    start_ready <= 1'b1;
                    internal_WE0 <= 1'b0;
                    if(out_done) begin
                        state <= STATE_OUTPUT;
                        internal_A <= 4'b0;
                    end
                end
                
                STATE_OUTPUT: begin
                    io_mode <= 1'b1;
                    internal_A <= output_cnt;
                    
                    if(read_pipeline == 3'd4) begin
                        X_real_r <= A_pr;
                        X_imag_r <= A_pi;
                        in_valid_r <= 1'b1;
                        
                        if(out_ready) begin
                            read_pipeline <= 0;
                            if(output_cnt == 4'd15) begin
                                state <= STATE_LOAD;
                                load_samples_cnt <= 4'b0;
                                output_cnt <= 0;
                            end else begin 
                                output_cnt <= output_cnt + 1;
                            end
                        end
                    end else begin
                        in_valid_r <= 1'b0;
                        read_pipeline <= read_pipeline + 1;
                    end
                end
                
            endcase
            
        end
        
    end

endmodule